import Cards from "./components/Cards";

const jobs = [
  {
    company: "Apple",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    days: "3 days ago",
    role: "iOS Developer",
    time: "Full-Time",
    level: "Mid Level",
    salary: "$125-160k",
    location: "Bengaluru",
  },
  {
    company: "TCS",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvaqBimiU40nIz5pLpegfCPkoQTp9_70-fLQS4PQa1sA&s=10",
    days: "6 days ago",
    role: "Full Stack Developer",
    time: "Full-Time",
    level: "Junior Level",
    salary: "$70-100k",
    location: "Noida",
  },
  {
    company: "Infosys",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg",
    days: "4 days ago",
    role: "Software Engineer",
    time: "Full-Time",
    level: "Entry Level",
    salary: "$65-95k",
    location: "Pune",
  },
  {
    company: "Accenture",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Accenture.svg",
    days: "9 days ago",
    role: "Frontend Developer",
    time: "Hybrid",
    level: "Mid Level",
    salary: "$90-125k",
    location: "Gurugram",
  },
  {
    company: "Flipkart",
    logo: "https://static.vecteezy.com/system/resources/previews/054/650/802/non_2x/flipkart-logo-rounded-flipkart-logo-free-download-flipkart-logo-free-png.png",
    days: "1 day ago",
    role: "Backend Developer",
    time: "Full-Time",
    level: "Junior Level",
    salary: "$80-115k",
    location: "Bengaluru",
  },
  {
    company: "Wipro",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg",
    days: "15 days ago",
    role: "React Developer",
    time: "Remote",
    level: "Mid Level",
    salary: "$75-110k",
    location: "Hyderabad",
  },
  {
    company: "Deloitte",
    logo: "https://banner2.cleanpng.com/20190226/ybz/kisspng-health-care-deloitte-salzburg-physician-5c75b2618ff261.5968037415512172495896.jpg",
    days: "11 days ago",
    role: "Business Analyst",
    time: "Full-Time",
    level: "Senior Level",
    salary: "$100-135k",
    location: "Mumbai",
  },
  {
    company: "Paytm",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/42/Paytm_logo.png",
    days: "5 days ago",
    role: "Node.js Developer",
    time: "Full-Time",
    level: "Entry Level",
    salary: "$70-105k",
    location: "Noida",
  },
  {
    company: "Amazon",
    logo: "https://images.seeklogo.com/logo-png/40/2/amazon-icon-logo-png_seeklogo-405254.png",
    days: "5 days ago",
    role: "Senior UI/UX Designer",
    time: "Part-Time",
    level: "Senior Level",
    salary: "$120/hr",
    location: "Mumbai",
  },
  {
    company: "Google",
    logo: "https://media.wired.com/photos/5926ffe47034dc5f91bed4e8/3:2/w_2560,c_limit/google-logo.jpg",
    days: "30 days ago",
    role: "Graphic Designer",
    time: "Part-Time",
    level: "Flexible Schedule",
    salary: "$150-220k",
    location: "Kochi",
  },
  {
    company: "Microsoft",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    days: "18 days ago",
    role: "Project Manager",
    time: "Full-Time",
    level: "Remote",
    salary: "$85/hr",
    location: "Chennai",
  },
  {
    company: "Adobe",
    logo: "https://static.vecteezy.com/system/resources/previews/060/100/962/non_2x/white-adobe-logo-square-rounded-adobe-logo-adobe-logo-free-download-free-png.png",
    days: "8 days ago",
    role: "Frontend Developer",
    time: "Full-Time",
    level: "Mid Level",
    salary: "$110-140k",
    location: "Pune",
  },
  {
    company: "Netflix",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    days: "12 days ago",
    role: "React Developer",
    time: "Remote",
    level: "Senior Level",
    salary: "$180-220k",
    location: "Bengaluru",
  },
  {
    company: "Meta",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png",
    days: "2 days ago",
    role: "Software Engineer",
    time: "Full-Time",
    level: "Entry Level",
    salary: "$130-170k",
    location: "Hyderabad",
  },
  {
    company: "IBM",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
    days: "7 days ago",
    role: "Backend Developer",
    time: "Full-Time",
    level: "Junior Level",
    salary: "$95-125k",
    location: "Noida",
  },
  {
    company: "Oracle",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg",
    days: "10 days ago",
    role: "Java Developer",
    time: "Hybrid",
    level: "Mid Level",
    salary: "$105-145k",
    location: "Gurugram",
  },
];

const App = () => {
  return (
    <div className="parent">
      {jobs.map((job, index) => (
        <Cards key={index} {...job} />
      ))}
    </div>
  );
};

export default App;
